# Generated by Django 2.2.3 on 2019-09-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='features',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
